import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-brand-beige">
      <div className="max-w-2xl mx-auto px-6 py-12 sm:py-20">
        <Link
          href="/"
          className="text-xl font-bold text-brand-dark mb-10 block"
        >
          moniz<span className="text-brand-accent">.</span>
        </Link>

        <h1 className="text-3xl font-bold text-brand-dark tracking-tight">
          Terms of Use
        </h1>
        <p className="text-sm text-brand-dark/40 mt-2">
          Last updated: April 2026
        </p>

        <div className="mt-10 space-y-8 text-sm text-brand-dark/60 leading-relaxed">
          <Section title="1. Acceptance">
            <p>
              By creating an account or using Moniz, you agree to these Terms
              of Use. If you do not agree, do not use the app.
            </p>
          </Section>

          <Section title="2. What Moniz is">
            <p>
              Moniz is a personal budgeting tool that helps students track
              spending, set budgets, and review spending patterns. It is a
              self-service tool — not a financial advisor, investment
              platform, or banking service.
            </p>
          </Section>

          <Section title="3. No financial advice">
            <p>
              Moniz does not provide financial, investment, tax, or legal
              advice. All insights, suggestions, and observations generated by
              the app are informational only and based on data you enter. You
              should not rely on Moniz as a substitute for professional
              financial guidance.
            </p>
          </Section>

          <Section title="4. Your account">
            <p>
              You are responsible for maintaining the security of your account
              credentials. You agree to provide accurate information during
              registration and to keep your account details up to date.
            </p>
            <p className="mt-2">
              One account per person. Do not share your login credentials with
              others.
            </p>
          </Section>

          <Section title="5. Acceptable use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Use Moniz for illegal purposes</li>
              <li>
                Attempt to access other users&apos; data or circumvent
                security measures
              </li>
              <li>
                Submit false, misleading, or harmful content
              </li>
              <li>
                Interfere with or disrupt the app&apos;s infrastructure
              </li>
              <li>
                Reverse engineer, scrape, or misuse the service
              </li>
            </ul>
          </Section>

          <Section title="6. Your data">
            <p>
              You own the financial data you enter into Moniz. We do not claim
              ownership of your expenses, budgets, or personal information.
              See our{" "}
              <Link
                href="/privacy"
                className="text-brand-accent underline"
              >
                Privacy Policy
              </Link>{" "}
              for details on how your data is handled.
            </p>
          </Section>

          <Section title="7. Availability">
            <p>
              We aim to keep Moniz available and reliable, but we do not
              guarantee uninterrupted access. The service may be temporarily
              unavailable for maintenance or due to circumstances beyond our
              control.
            </p>
          </Section>

          <Section title="8. Limitation of liability">
            <p>
              Moniz is provided &ldquo;as is&rdquo; without warranties of any
              kind, express or implied. To the maximum extent permitted by
              law, we are not liable for any damages arising from your use of
              the app, including but not limited to financial losses,
              inaccurate data entry, or reliance on app-generated insights.
            </p>
          </Section>

          <Section title="9. Termination">
            <p>
              You may delete your account at any time through the app
              settings. We reserve the right to suspend or terminate accounts
              that violate these terms, with or without notice.
            </p>
          </Section>

          <Section title="10. Changes">
            <p>
              We may update these terms from time to time. Material changes
              will be communicated through the app. Continued use after
              changes constitutes acceptance.
            </p>
          </Section>

          <Section title="11. Contact">
            <p>
              Questions about these terms? Reach us at{" "}
              <span className="text-brand-dark font-medium">
                support@moniz.app
              </span>
              .
            </p>
          </Section>
        </div>

        <div className="mt-12 pt-8 border-t border-brand-dark/5 flex items-center justify-between text-xs text-brand-dark/30">
          <Link href="/" className="hover:text-brand-dark/60 transition-colors">
            Back to home
          </Link>
          <Link
            href="/privacy"
            className="hover:text-brand-dark/60 transition-colors"
          >
            Privacy Policy
          </Link>
        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <h2 className="text-base font-semibold text-brand-dark mb-2">
        {title}
      </h2>
      {children}
    </div>
  );
}
